/**
 * @file services/githubService.ts
 * @satisfies [REQ-PAT-007]
 * Creates a Pull Request on GitHub via the REST API.
 */

import fetch from 'node-fetch';
import { PullRequestResult, PatchFile, TestResult } from '../types';
import { PatchInputData } from '../schemas/patchSchema';
import logger from '../utils/logger';

const GITHUB_API = 'https://api.github.com';

interface GitHubPRResponse {
  number: number;
  html_url: string;
  created_at: string;
}

export async function createPullRequest(
  input: PatchInputData,
  branchName: string,
  patchFiles: PatchFile[],
  testResult: TestResult | null,
  traceId: string,
): Promise<PullRequestResult> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    throw new Error('PATCH_GITHUB_ERROR: GITHUB_TOKEN is not set');
  }

  const repo = input.target_agent.github_repo;
  const title = `[${input.patch_id}] ${input.assignment.type}: ${input.assignment.title}`;
  const body = buildPRBody(input, branchName, patchFiles, testResult);

  logger.info('Outbound request', {
    event: 'outbound_request',
    trace_id: traceId,
    target: 'github-api',
    method: 'POST',
    path: `/repos/${repo}/pulls`,
  });

  const startMs = Date.now();
  const response = await fetch(`${GITHUB_API}/repos/${repo}/pulls`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify({
      title,
      body,
      head: branchName,
      base: 'main',
      draft: false,
    }),
  });

  const duration = Date.now() - startMs;

  if (!response.ok) {
    const errorText = await response.text();
    logger.error('Outbound request failed', {
      event: 'outbound_error',
      trace_id: traceId,
      target: 'github-api',
      status_code: response.status,
      duration_ms: duration,
      error: errorText,
    });
    throw new Error(`PATCH_GITHUB_ERROR: GitHub API returned ${response.status} — ${errorText}`);
  }

  const pr = (await response.json()) as GitHubPRResponse;

  logger.info('Outbound response received', {
    event: 'outbound_response',
    trace_id: traceId,
    target: 'github-api',
    status_code: response.status,
    duration_ms: duration,
    pr_number: pr.number,
  });

  return {
    url: pr.html_url,
    number: pr.number,
    branch: branchName,
    title,
    created_at: pr.created_at,
  };
}

function buildPRBody(
  input: PatchInputData,
  branchName: string,
  patchFiles: PatchFile[],
  testResult: TestResult | null,
): string {
  const criteriaChecklist = input.assignment.acceptance_criteria
    .map((c) => `- [x] ${c}`)
    .join('\n');

  const changesTable = patchFiles
    .map((f) => `| \`${f.file_path}\` | ${f.action} | +${f.lines_added} / -${f.lines_removed} |`)
    .join('\n');

  const testSection = testResult
    ? `\`\`\`\n${testResult.output_summary}\n\`\`\``
    : '_Tests not run_';

  return `## Summary

${input.assignment.description}

## Assignment

- **Patch ID:** ${input.patch_id}
- **Type:** ${input.assignment.type}
- **Assigned by:** ${input.context.reported_by}
- **Priority:** ${input.context.priority}

## Changes

| File | Action | Lines Δ |
|------|--------|---------|
${changesTable}

## Acceptance Criteria

${criteriaChecklist}

## Test Results

${testSection}

---
🩹 Generated by [Pippin — DevOS Patch Agent](http://localhost:3014)`;
}
